<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SampleDataSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        // 1. Insert Master Customers
        $customers = [
            ['company_id' => 1, 'name' => 'AFF', 'code' => 'CUST001', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'AIRPORT DELIVERY', 'code' => 'CUST002', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'AROHI FLOWERS', 'code' => 'CUST003', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'AS FLOWERS', 'code' => 'CUST004', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'ASHIM FLOWERS', 'code' => 'CUST005', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'ASHOK MORE', 'code' => 'CUST006', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'BREMBO BRAKES', 'code' => 'CUST007', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'D.P FLOWERS', 'code' => 'CUST008', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'ESSAR', 'code' => 'CUST009', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'FAISAL FLOWERS', 'code' => 'CUST010', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'GAUTAM KUMAR', 'code' => 'CUST011', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'GOPAL ROY', 'code' => 'CUST012', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'HARI PAVLE', 'code' => 'CUST013', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'HARSHVARDHAN', 'code' => 'CUST014', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'KAIROSE INTERNATIONAL', 'code' => 'CUST015', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'KAKA PINGLE', 'code' => 'CUST016', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'LAXMI ENTERPRISES', 'code' => 'CUST017', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'MA LOGISTICS', 'code' => 'CUST018', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'MALEGAON FLOWERS', 'code' => 'CUST019', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'MALIKA', 'code' => 'CUST020', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'MALIKA FLORIST', 'code' => 'CUST021', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'MALLU', 'code' => 'CUST022', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'P.R FLORIST', 'code' => 'CUST023', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'PCF', 'code' => 'CUST024', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'POOJA FLORA', 'code' => 'CUST025', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'PRAGATI FLOWERS', 'code' => 'CUST026', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'PRAMOD(CHANDIGARH)', 'code' => 'CUST027', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'PRANJAL ROSES', 'code' => 'CUST028', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SACHIN TIWARI', 'code' => 'CUST029', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SAIROSES', 'code' => 'CUST030', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SARJU TIWARI', 'code' => 'CUST031', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SHRI HI TECH', 'code' => 'CUST032', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SOEX FLORA', 'code' => 'CUST033', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SOURAV', 'code' => 'CUST034', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SPRING TIME FLORA', 'code' => 'CUST035', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'SUNNY FLOWERS', 'code' => 'CUST036', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'VINOD TOMAR', 'code' => 'CUST037', 'is_active' => 1],
            ['company_id' => 1, 'name' => 'VIVEK SINGH', 'code' => 'CUST038', 'is_active' => 1],
        ];
        
        foreach ($customers as $c) {
            $existing = $db->table('customers')->where('name', $c['name'])->get()->getRow();
            if (!$existing) {
                $db->table('customers')->insert($c);
            }
        }

        // 2. Insert Master Airlines
        $airlines = [
        ];
        
        foreach ($airlines as $a) {
            $existing = $db->table('airlines')->where('code', $a['code'])->get()->getRow();
            if (!$existing) {
                $db->table('airlines')->insert($a);
            }
        }

        // 3. Insert Master Lookup Values
        $lookups = [
            ['company_id' => 1, 'type' => 'origin', 'value' => 'PNQ', 'sort_order' => 1],
            ['company_id' => 1, 'type' => 'origin', 'value' => 'PUNE', 'sort_order' => 2],
            ['company_id' => 1, 'type' => 'destination', 'value' => 'DEL', 'sort_order' => 1],
            ['company_id' => 1, 'type' => 'destination', 'value' => 'IXB VIA CCU', 'sort_order' => 2],
            ['company_id' => 1, 'type' => 'destination', 'value' => 'MAA', 'sort_order' => 3],
            ['company_id' => 1, 'type' => 'payment_type', 'value' => 'AIR', 'sort_order' => 1],
            ['company_id' => 1, 'type' => 'payment_type', 'value' => 'CASH', 'sort_order' => 2],
            ['company_id' => 1, 'type' => 'payment_type', 'value' => 'GST BILL', 'sort_order' => 3],
            ['company_id' => 1, 'type' => 'payment_type', 'value' => 'TO PAY', 'sort_order' => 4],
            ['company_id' => 1, 'type' => 'payment_type', 'value' => 'WITHOUT GST', 'sort_order' => 5],
            ['company_id' => 1, 'type' => 'material_category', 'value' => 'FLOWERS', 'sort_order' => 1],
            ['company_id' => 1, 'type' => 'material_type', 'value' => 'FLOWERS', 'sort_order' => 1],
        ];

        foreach ($lookups as $l) {
            $existing = $db->table('lookup_values')
                           ->where('type', $l['type'])
                           ->where('value', $l['value'])
                           ->get()->getRow();
            if (!$existing) {
                $db->table('lookup_values')->insert($l);
            }
        }

        // 4. Insert Bookings, Shipment Items & Sales Charges
        $userId = 1; // Admin user ID

        // Booking AWB 4561712
        $bookingData = [
            'awb_no' => '4561712',
            'company_id' => 1,
            'booking_date' => '2026-05-01',
            'origin' => 'PNQ',
            'destination' => 'DEL',
            'mode_transport' => 'Air',
            'material_type' => 'FLOWERS',
            'material_category' => 'FLOWERS',
            'total_pieces' => 40,
            'total_weight' => 604.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Booked',
            'payment_type' => 'TO PAY',
            'narration' => '',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SAIROSES',
            'bill_to' => 'ASHIM FLOWERS',
            'consignee' => 'ASHIM FLOWERS',
            'docket_no' => '4561712',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 63.0,
            'calculated_chargeable_weight' => 63.0,
            'final_chargeable_weight' => 63.0,
            'pieces' => 4,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SAIROSES',
            'bill_to' => 'PRAGATI FLOWERS',
            'consignee' => 'PRAGATI FLOWERS',
            'docket_no' => '4561712',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 107.0,
            'calculated_chargeable_weight' => 107.0,
            'final_chargeable_weight' => 107.0,
            'pieces' => 7,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SAIROSES',
            'bill_to' => 'VIVEK SINGH',
            'consignee' => 'KAIROSE INTERNATIONAL',
            'docket_no' => '4561712',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 186.0,
            'calculated_chargeable_weight' => 186.0,
            'final_chargeable_weight' => 186.0,
            'pieces' => 12,
            'rate' => 32.79,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SAIROSES',
            'bill_to' => 'SARJU TIWARI',
            'consignee' => 'SARJU TIWARI',
            'docket_no' => '4561712',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 46.0,
            'calculated_chargeable_weight' => 46.0,
            'final_chargeable_weight' => 46.0,
            'pieces' => 3,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'HARI PAVLE',
            'bill_to' => 'SACHIN TIWARI',
            'consignee' => 'SACHIN TIWARI',
            'docket_no' => '4561712',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 165.0,
            'calculated_chargeable_weight' => 165.0,
            'final_chargeable_weight' => 165.0,
            'pieces' => 11,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'HARSHVARDHAN',
            'bill_to' => 'VIVEK SINGH',
            'consignee' => 'KAIROSE INTERNATIONAL',
            'docket_no' => '4561712',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 40.0,
            'calculated_chargeable_weight' => 40.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 3,
            'rate' => 32.79,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 4545892
        $bookingData = [
            'awb_no' => '4545892',
            'company_id' => 1,
            'booking_date' => '2026-05-01',
            'origin' => 'PNQ',
            'destination' => 'DEL',
            'mode_transport' => 'Air',
            'material_type' => 'FLOWERS',
            'material_category' => 'FLOWERS',
            'total_pieces' => 65,
            'total_weight' => 916.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Booked',
            'payment_type' => 'TO PAY',
            'narration' => '',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'AS FLOWERS',
            'bill_to' => 'SARJU TIWARI',
            'consignee' => 'SARJU TIWARI',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 60.0,
            'calculated_chargeable_weight' => 60.0,
            'final_chargeable_weight' => 60.0,
            'pieces' => 4,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SHRI HI TECH',
            'bill_to' => 'FAISAL FLOWERS',
            'consignee' => 'FAISAL FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 70.0,
            'calculated_chargeable_weight' => 70.0,
            'final_chargeable_weight' => 70.0,
            'pieces' => 5,
            'rate' => 45.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'KAKA PINGLE',
            'bill_to' => 'PRAMOD(CHANDIGARH)',
            'consignee' => 'PRAMOD(CHANDIGARH)',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 82.0,
            'calculated_chargeable_weight' => 82.0,
            'final_chargeable_weight' => 82.0,
            'pieces' => 7,
            'rate' => 45.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'PRANJAL ROSES',
            'bill_to' => 'FAISAL FLOWERS',
            'consignee' => 'FAISAL FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 60.0,
            'calculated_chargeable_weight' => 60.0,
            'final_chargeable_weight' => 60.0,
            'pieces' => 4,
            'rate' => 45.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'AFF',
            'bill_to' => 'ASHIM FLOWERS',
            'consignee' => 'ASHIM FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 49.0,
            'calculated_chargeable_weight' => 49.0,
            'final_chargeable_weight' => 49.0,
            'pieces' => 3,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'MALEGAON FLOWERS',
            'bill_to' => 'VINOD TOMAR',
            'consignee' => 'VINOD TOMAR',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 34.0,
            'calculated_chargeable_weight' => 34.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 2,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'D.P FLOWERS',
            'bill_to' => 'VIVEK SINGH',
            'consignee' => 'P.R FLORIST',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 13.0,
            'calculated_chargeable_weight' => 13.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 1,
            'rate' => 32.79,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SOEX FLORA',
            'bill_to' => 'MALIKA FLORIST',
            'consignee' => 'MALIKA',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 201.0,
            'calculated_chargeable_weight' => 201.0,
            'final_chargeable_weight' => 201.0,
            'pieces' => 12,
            'rate' => 36.356,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SOEX FLORA',
            'bill_to' => 'VIVEK SINGH',
            'consignee' => 'VIVEK SINGH',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 226.0,
            'calculated_chargeable_weight' => 226.0,
            'final_chargeable_weight' => 226.0,
            'pieces' => 15,
            'rate' => 32.79,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'POOJA FLORA',
            'bill_to' => 'ASHIM FLOWERS',
            'consignee' => 'ASHIM FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 15.0,
            'calculated_chargeable_weight' => 15.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 1,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'AROHI FLOWERS',
            'bill_to' => 'SUNNY FLOWERS',
            'consignee' => 'SUNNY FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 19.0,
            'calculated_chargeable_weight' => 19.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 1,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SPRING TIME FLORA',
            'bill_to' => 'SUNNY FLOWERS',
            'consignee' => 'SUNNY FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 34.0,
            'calculated_chargeable_weight' => 34.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 2,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'ESSAR',
            'bill_to' => 'VINOD TOMAR',
            'consignee' => 'VINOD TOMAR',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 35.0,
            'calculated_chargeable_weight' => 35.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 2,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'ESSAR',
            'bill_to' => 'PRAGATI FLOWERS',
            'consignee' => 'PRAGATI FLOWERS',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 16.0,
            'calculated_chargeable_weight' => 16.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 1,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'ASHOK MORE',
            'bill_to' => 'ASHOK MORE',
            'consignee' => 'AIRPORT DELIVERY',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 28.0,
            'calculated_chargeable_weight' => 28.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 2,
            'rate' => 45.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'MALLU',
            'bill_to' => 'MALLU',
            'consignee' => 'GAUTAM KUMAR',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 4.0,
            'calculated_chargeable_weight' => 4.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 1,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'SOURAV',
            'bill_to' => 'SOURAV',
            'consignee' => 'LAXMI ENTERPRISES',
            'docket_no' => '4545892',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 40.0,
            'calculated_chargeable_weight' => 40.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 3,
            'rate' => 40.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 27243370
        $bookingData = [
            'awb_no' => '27243370',
            'company_id' => 1,
            'booking_date' => '2026-05-02',
            'origin' => 'PNQ',
            'destination' => 'IXB VIA CCU',
            'mode_transport' => 'Air',
            'material_type' => 'FLOWERS',
            'material_category' => 'FLOWERS',
            'total_pieces' => 5,
            'total_weight' => 75.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Booked',
            'payment_type' => 'CASH',
            'narration' => '',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'MA LOGISTICS',
            'bill_to' => 'GOPAL ROY',
            'consignee' => 'GOPAL ROY',
            'docket_no' => '27243370',
            'part_no' => '',
            'invoice_no' => '',
            'actual_weight' => 75.0,
            'calculated_chargeable_weight' => 75.0,
            'final_chargeable_weight' => 75.0,
            'pieces' => 5,
            'rate' => 0.0,
            'delivery_charges' => 0.0,
            'docket_charges' => 0.0,
            'pickup_charges' => 0.0,
            'fuel_surcharge' => 0.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51627
        $bookingData = [
            'awb_no' => '51627',
            'company_id' => 1,
            'booking_date' => '2026-05-01',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 31,
            'total_weight' => 683.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/065',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51627',
            'part_no' => '22W34470',
            'invoice_no' => '36006523',
            'actual_weight' => 402.79,
            'calculated_chargeable_weight' => 402.79,
            'final_chargeable_weight' => 402.79,
            'pieces' => 276,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 1707.5,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51627',
            'part_no' => '22W35030',
            'invoice_no' => '36006524',
            'actual_weight' => 280.21,
            'calculated_chargeable_weight' => 280.21,
            'final_chargeable_weight' => 280.21,
            'pieces' => 192,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 1707.5,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 683.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 3415.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 38099.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51628
        $bookingData = [
            'awb_no' => '51628',
            'company_id' => 1,
            'booking_date' => '2026-05-02',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 18,
            'total_weight' => 228.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/065',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51628',
            'part_no' => '22W15312',
            'invoice_no' => '36006648',
            'actual_weight' => 72.0,
            'calculated_chargeable_weight' => 72.0,
            'final_chargeable_weight' => 72.0,
            'pieces' => 96,
            'rate' => 48.0,
            'delivery_charges' => 300.0,
            'docket_charges' => 33.333333333333336,
            'pickup_charges' => 300.0,
            'fuel_surcharge' => 380.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51628',
            'part_no' => '10W12086',
            'invoice_no' => '36006649',
            'actual_weight' => 81.0,
            'calculated_chargeable_weight' => 81.0,
            'final_chargeable_weight' => 81.0,
            'pieces' => 108,
            'rate' => 48.0,
            'delivery_charges' => 300.0,
            'docket_charges' => 33.333333333333336,
            'pickup_charges' => 300.0,
            'fuel_surcharge' => 380.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51628',
            'part_no' => '26W11038',
            'invoice_no' => '36006650',
            'actual_weight' => 75.0,
            'calculated_chargeable_weight' => 75.0,
            'final_chargeable_weight' => 75.0,
            'pieces' => 100,
            'rate' => 48.0,
            'delivery_charges' => 300.0,
            'docket_charges' => 33.333333333333336,
            'pickup_charges' => 300.0,
            'fuel_surcharge' => 380.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 228.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 1140.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 13984.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51629
        $bookingData = [
            'awb_no' => '51629',
            'company_id' => 1,
            'booking_date' => '2026-05-03',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 20,
            'total_weight' => 340.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/065',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51629',
            'part_no' => '22W34470',
            'invoice_no' => '36006704',
            'actual_weight' => 170.0,
            'calculated_chargeable_weight' => 170.0,
            'final_chargeable_weight' => 170.0,
            'pieces' => 120,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 850.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51629',
            'part_no' => '22W34470',
            'invoice_no' => '36006730',
            'actual_weight' => 170.0,
            'calculated_chargeable_weight' => 170.0,
            'final_chargeable_weight' => 170.0,
            'pieces' => 120,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 850.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 340.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 1700.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 19920.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51630
        $bookingData = [
            'awb_no' => '51630',
            'company_id' => 1,
            'booking_date' => '2026-05-03',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 25,
            'total_weight' => 504.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/081',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51630',
            'part_no' => '22W34470',
            'invoice_no' => '36006758',
            'actual_weight' => 237.18,
            'calculated_chargeable_weight' => 237.18,
            'final_chargeable_weight' => 237.18,
            'pieces' => 192,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 1260.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51630',
            'part_no' => '22W15312',
            'invoice_no' => '36006777',
            'actual_weight' => 266.82,
            'calculated_chargeable_weight' => 266.82,
            'final_chargeable_weight' => 266.82,
            'pieces' => 216,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 1260.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 504.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 2520.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 28612.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51631
        $bookingData = [
            'awb_no' => '51631',
            'company_id' => 1,
            'booking_date' => '2026-05-03',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 34,
            'total_weight' => 396.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/081',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51631',
            'part_no' => '10W12086',
            'invoice_no' => '36006802',
            'actual_weight' => 241.46,
            'calculated_chargeable_weight' => 241.46,
            'final_chargeable_weight' => 241.46,
            'pieces' => 300,
            'rate' => 48.0,
            'delivery_charges' => 300.0,
            'docket_charges' => 33.333333333333336,
            'pickup_charges' => 300.0,
            'fuel_surcharge' => 660.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51631',
            'part_no' => '22W35035',
            'invoice_no' => '36006821',
            'actual_weight' => 86.93,
            'calculated_chargeable_weight' => 86.93,
            'final_chargeable_weight' => 86.93,
            'pieces' => 108,
            'rate' => 48.0,
            'delivery_charges' => 300.0,
            'docket_charges' => 33.333333333333336,
            'pickup_charges' => 300.0,
            'fuel_surcharge' => 660.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51631',
            'part_no' => '22W15312',
            'invoice_no' => '36006820',
            'actual_weight' => 67.61,
            'calculated_chargeable_weight' => 67.61,
            'final_chargeable_weight' => 67.61,
            'pieces' => 84,
            'rate' => 48.0,
            'delivery_charges' => 300.0,
            'docket_charges' => 33.333333333333336,
            'pickup_charges' => 300.0,
            'fuel_surcharge' => 660.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 396.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 1980.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 22888.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51632
        $bookingData = [
            'awb_no' => '51632',
            'company_id' => 1,
            'booking_date' => '2026-05-04',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 9,
            'total_weight' => 65.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/081',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51632',
            'part_no' => '26W11038',
            'invoice_no' => '36006980',
            'actual_weight' => 65.0,
            'calculated_chargeable_weight' => 65.0,
            'final_chargeable_weight' => 65.0,
            'pieces' => 180,
            'rate' => 48.0,
            'delivery_charges' => 900.0,
            'docket_charges' => 100.0,
            'pickup_charges' => 900.0,
            'fuel_surcharge' => 325.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 65.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 325.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 5345.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51349
        $bookingData = [
            'awb_no' => '51349',
            'company_id' => 1,
            'booking_date' => '2026-05-04',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 20,
            'total_weight' => 130.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/081',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51349',
            'part_no' => '26W12086',
            'invoice_no' => '36006951',
            'actual_weight' => 83.57,
            'calculated_chargeable_weight' => 83.57,
            'final_chargeable_weight' => 83.57,
            'pieces' => 180,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 325.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51349',
            'part_no' => '26W11038',
            'invoice_no' => '36006952',
            'actual_weight' => 46.43,
            'calculated_chargeable_weight' => 46.43,
            'final_chargeable_weight' => 46.43,
            'pieces' => 100,
            'rate' => 48.0,
            'delivery_charges' => 450.0,
            'docket_charges' => 50.0,
            'pickup_charges' => 450.0,
            'fuel_surcharge' => 325.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 130.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 650.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 8790.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51633
        $bookingData = [
            'awb_no' => '51633',
            'company_id' => 1,
            'booking_date' => '2026-05-05',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 4,
            'total_weight' => 29.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/067',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51633',
            'part_no' => '26W11038',
            'invoice_no' => '36007036',
            'actual_weight' => 29.0,
            'calculated_chargeable_weight' => 29.0,
            'final_chargeable_weight' => 45.0,
            'pieces' => 80,
            'rate' => 48.0,
            'delivery_charges' => 900.0,
            'docket_charges' => 100.0,
            'pickup_charges' => 900.0,
            'fuel_surcharge' => 145.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 29.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 145.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 3437.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51634
        $bookingData = [
            'awb_no' => '51634',
            'company_id' => 1,
            'booking_date' => '2026-05-05',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 45,
            'total_weight' => 378.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/067',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51634',
            'part_no' => '10W31545',
            'invoice_no' => '36007208',
            'actual_weight' => 378.0,
            'calculated_chargeable_weight' => 378.0,
            'final_chargeable_weight' => 378.0,
            'pieces' => 540,
            'rate' => 48.0,
            'delivery_charges' => 900.0,
            'docket_charges' => 100.0,
            'pickup_charges' => 900.0,
            'fuel_surcharge' => 1890.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 378.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 1890.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 21934.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // Booking AWB 51350
        $bookingData = [
            'awb_no' => '51350',
            'company_id' => 1,
            'booking_date' => '2026-05-05',
            'origin' => 'PUNE',
            'destination' => 'MAA',
            'mode_transport' => 'Air',
            'material_type' => 'AUTO PART',
            'material_category' => 'AUTO PART',
            'total_pieces' => 29,
            'total_weight' => 441.0,
            'flight_number' => '',
            'airlines' => '',
            'status' => 'Billed',
            'payment_type' => 'Credit',
            'narration' => 'MA Bill: MA/26-27/067',
            'created_by' => $userId,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $db->table('bookings')->insert($bookingData);
        $bookingId = $db->insertID();
        $db->table('shipment_items')->insert([
            'booking_id' => $bookingId,
            'customer_name' => 'BREMBO BRAKES',
            'bill_to' => 'BREMBO BRAKES',
            'consignee' => 'BREMBO BRAKES',
            'docket_no' => '51350',
            'part_no' => '22W15312',
            'invoice_no' => '36007156',
            'actual_weight' => 441.0,
            'calculated_chargeable_weight' => 441.0,
            'final_chargeable_weight' => 441.0,
            'pieces' => 324,
            'rate' => 48.0,
            'delivery_charges' => 900.0,
            'docket_charges' => 100.0,
            'pickup_charges' => 900.0,
            'fuel_surcharge' => 2205.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        $db->table('sales_charges')->insert([
            'booking_id' => $bookingId,
            'flight_number' => '',
            'airlines' => '',
            'rate' => 48.0,
            'weight' => 441.0,
            'ddc' => 900.0,
            'ssc' => 0.00,
            'btc' => 0.00,
            'flc' => 2205.0,
            'doc' => 100.0,
            'inbound_tsp' => 900.0,
            'utility_charges' => 0.00,
            'xray_charges' => 0.00,
            'awb_fees_agent' => 0.00,
            'awb_fees_carrier' => 0.00,
            'admin_charges' => 0.00,
            'delivery_order_charges' => 0.00,
            'inbound_handling' => 0.00,
            'inbound_storage' => 0.00,
            'outbound_storage' => 0.00,
            'misc_charges' => 0.00,
            'total_amount' => 25273.0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
    }
}
